import { headers } from "next/headers"

import { GeistMono, GeistSans } from "geist/font"
import { Toaster as ToastProvider } from "sonner"

import "@/styles/globals.css"
import { TRPCReactProvider } from "@/trpc/react"

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang="en"
			className={`${GeistSans.variable} ${GeistMono.variable}`}
		>
			<body>
				<TRPCReactProvider headers={headers()}>
					{children}
					<ToastProvider richColors />
				</TRPCReactProvider>
			</body>
		</html>
	)
}
